class Rotor {
    constructor(name, inputLetters, ouputLetters, notchLetters) {
        this.name = name;
        this.inputLetters = inputLetters.split('');
        this.outputLetters = outputLetters.split('');
        if (notchLetters !== "") {
            this.notchLetters = notchLetters.split('');
        };
    }
}

var rortor = [
    new Rotor("I", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "EKMFLGDQVZNTOWYHXUSPAIBRCJ", "Q"),
    new Rotor("II", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "AJDKSIRUXBLHWTMCQGZNPYFVOE", "E"),
    new Rotor("III", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "BDFHJLCPRTXVZNYEIWGAKMUSQO", "V"),
    new Rotor("IV", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ESOVPZJAYQUIRHXLNFTGKDCMWB", "J"),
    new Rotor("V", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "VZBRGITYUPSDNHLXAWMJQOFECK", "Z"),
    new Rotor("VI", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "JPGVOUMFYQBENHZRDKASXLICTW", "MZ"),
    new Rotor("VII", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NZJHGRCXMYSWBOUFAIVLPEKQDT", "MZ"),
    new Rotor("VIII", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "FKQHTLXOCBJSPDZRAMEWNIUYGV", "MZ")
];

var reflector = [
    new Rotor("Beta", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "LEYJVCNIXWPBQMDRTAKZGFUHOS", ""),
    new Rotor("Gamma", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "FSOKANUERHMBTIYCWLQPZXVGJD", ""),
    new Rotor("Reflector A", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "EJMZALYXVBWFCRQUONTSPIKHGD", ""),
    new Rotor("Reflector B", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "YRUHQSLDPXNGOKMIEBFZCWVJAT", ""),
    new Rotor("Reflector C", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "FVPJIAOYEDRZXWGCTKUQSBNMHL", ""),
    new Rotor("Reflector B Thin", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ENKQAUYWJICOPBLMDXZVFTHRGS", ""),
    new Rotor("Reflector C Thin", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "RDOBJNTKVEHMLFCWZAXGYIPSUQ", ""),
    new Rotor("ETW", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "")
];